### ISSUE TITLE
Compile error on linux

### ISSUE THREAD

**Issue by Blavion** [OpenAnnePro/AnnePro2-Tools#18]
Hi when I try to manually compile the program on Manjaro Linux Kernel 6.4.2-3 I get an error.

### The error.     

When I compile the program  I get the following ouput:                                                                                                                    
"warning: dependency (hidapi) specified without providing a local path, Git repository, or version to use. This will be considered
 an error in future versions
   Compiling annepro2_tools v0.1.0 (My-project-path)
error[E0599]: no method named \`usage\` found for reference \`&DeviceInfo\` in the current scope
   --> src/annepro2.rs:111:17
    |
111 |             dev.usage(),
    |                 ^^^^^ private field, not a method

error[E0599]: no method named \`usage_page\` found for reference \`&DeviceInfo\` in the current scope
   --> src/annepro2.rs:112:17
    |
112 |             dev.usage_page(),
    |                 ^^^^^^^^^^ private field, not a method

For more information about this error, try `rustc --explain E0599`.
error: could not compile `annepro2_tools` (bin "annepro2_tools") due to 2 previous errors"

I found that the newer versions of hidapi does not have those methods. It has private fields instead.

### The solution.

In the `Cargo.toml` I added a specific earlier version of hidapi. Since i could see that some of the project was 3 years old I took a 3 year old version. 

Under `[dependencies]`
Put: 
`hidapi = {version = "1.2.3", default-features = false, features = ["linux-static-libusb"]}`

Instead of 

`hidapi = {default-features = false, features = ["linux-static-libusb"]}`

It now compiles.

**Comment by ghost** [comment]
> I found that the newer versions of hidapi does not have those methods. It has private fields instead.

Actually, it has. [But not for linux](https://github.com/ruabmbua/hidapi-rs/blob/78f273800a7e9fc7f428e45d2cfebaf7b44862c1/src/lib.rs#L379).

I find removing usage and usage_page from the print better, than downgrading the library.
