### ISSUE TITLE
Build issue with hidapi

### ISSUE THREAD

**Issue by jameskeim** [OpenAnnePro/AnnePro2-Tools#2]
This is probably only something I've neglected to install but I can't seem to build the Tools because of the following error.

    error: failed to run custom build command for `hidapi v1.2.3`

    process didn't exit successfully: `~/builds/annepro2/AnnePro2-Tools/target/release/build/hidapi-27c1822486569db1/build-script-build` (exit code: 101)
    --- stderr
    thread 'main' panicked at 'Unable to find libusb-1.0: "`\"pkg-config\" \"--libs\" \"--cflags\" \"libusb-1.0\"` did not exit successfully: 
    exit code: 1\n--- stderr\nPackage libusb-1.0 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libusb-1.0.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'libusb-1.0\' found\n"', 
    ~/.cargo/registry/src/github.com-1ecc6299db9ec823/hidapi-1.2.3/build.rs:65:21
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

    warning: build failed, waiting for other jobs to finish...

**Comment by Codetector1374** [comment]
You might be missing libusb try to install libusb(-dev)

**Comment by jameskeim** [comment]
Interesting. I had installed libusb-dev on both Windows WSL2/Ubuntu and on Pop!OS but still couldn't get it to work. Went back and found the line requesting libusb in "hidapi-1.2.3/build.rs" and it is specifically looking for libusb-1.0-0-dev. Easy to apt install but just installing libusb-dev installs version 2.0. Thanks for prompting me to go back and look at it again! 

> You might be missing libusb try to install libusb(-dev)

**Comment by Codetector1374** [comment]
cool. If it works now you can close the issue.

**Comment by sakura-he** [comment]
+1
I also encountered the same error during compilation. The compilation environment: centos, ubuntu, debian, wsl-ubuntu, wsl-debin.
I tried to install libusb-1.0-0-dev and libusb-dev and still reported an error

**Comment by sakura-he** [comment]
Error message
```
Package libusb-1:0.1.5-12.el8.x86_64 is already installed.                      
Dependencies resolved.                                                          
Nothing to do.                                                                  
Complete!                                                                       
[root@centos1 AnnePro2-Tools]# cargo build --release                            
   Compiling hidapi v1.2.3                                                      
   Compiling proc-macro-error-attr v1.0.3                                       
error: failed to run custom build command for `hidapi v1.2.3`                   
                                                                                
Caused by:                                                                      
  process didn't exit successfully: `/AnnePro2-Tools/target/release/build/hidapi
-4b269d968da30fda/build-script-build` (exit code: 101)                          
  --- stderr                                                                    
  thread 'main' panicked at 'Unable to find libusb-1.0: "`\"pkg-config\" \"--lib
s\" \"--cflags\" \"libusb-1.0\"` did not exit successfully: exit code: 1\n--- st
derr\nPackage libusb-1.0 was not found in the pkg-config search path.\nPerhaps y
ou should add the directory containing `libusb-1.0.pc\'\nto the PKG_CONFIG_PATH 
environment variable\nPackage \'libusb-1.0\', required by \'virtual:world\', not
 found\n"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/hidapi-1.2.3/b
uild.rs:65:60                                                                   
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 
warning: build failed, waiting for other jobs to finish...                      
error: build failed                                                             
```

**Comment by sakura-he** [comment]
> 凉。如果现在可以使用，则可以解决问题。

Can you create a compiled release it?thank you
I tried my best, but still no success

**Comment by Codetector1374** [comment]
sure I can provide a windows binary (soon, probably some time this week. Kind of busy right now)

**Comment by sakura-he** [comment]
非常感谢，

> sure I can provide a windows binary (soon, probably some time this week. Kind of busy right now)

Thank you very much,

**Comment by sakura-he** [comment]
> sure I can provide a windows binary (soon, probably some time this week. Kind of busy right now)

Thank you very much,

**Comment by aliveoutside** [comment]
Try to install pkg-config, it helped me

sudo apt install pkg-config on Ubuntu/Debian

**Comment by sakura-he** [comment]
> Try to install pkg-config, it helped me
> 
> 
> 
> sudo apt install pkg-config on Ubuntu/Debian
> 
> 

Thank you for your reply. I found the compiled binary file at the URL in the description a few days ago. I will try again in the way you provided.

**Comment by Metaln00b** [comment]
Problem still exists on WSL2
