### ISSUE TITLE
bash: annepro2_tools command not found

### ISSUE THREAD

**Issue by carinafan** [OpenAnnePro/AnnePro2-Tools#9]
Hi there, I'm trying to use AnnePro2-Tools to flash QMK but for some reason the tool is not running. It looks like it's compiled fine and I'm running it from the directory that it lives in. Is there some thing obvious I'm missing?

Thank you in advance!

```
~/Documents/AnnePro2-Tools-master/target/release$ ls
annepro2_c18_default.bin* annepro2_tools.d          deps/                     incremental/
annepro2_tools*           build/                    examples/
```

```
~/Documents/AnnePro2-Tools-master/target/release$ annepro2_tools annepro2_c15_default.bin
-bash: annepro2_tools: command not found
```

**Comment by Nanoseb** [comment]
Does it work by running `./annepro2_tools annepro2_c15_default.bin` instead?

**Comment by carinafan** [comment]
It sure does! Thank you so much!
